### ISSUE TITLE
can you give a json that i can use you plugins

### ISSUE THREAD

**Issue by Rigaln** [rennerdo30/ffxiv-simplecompare#1]
can you give a json that i can use you plugins

**Comment by rennerdo30** [comment]
My own plugin repo can be found here:
https://github.com/Rennerdo30/MyDalamudPlugins

The JSON would be https://raw.githubusercontent.com/Rennerdo30/MyDalamudPlugins/main/pluginmaster.json
There are some other plugins in it besides SimpleCompare.
