### ISSUE TITLE
Prevent SimpleCompare details from taking focus from other Imgui windows

### ISSUE THREAD

**Issue by MidoriKami** [rennerdo30/ffxiv-simplecompare#3]
https://github.com/Rennerdo30/ffxiv-simplecompare/blob/main/SimpleCompare/PluginUI.cs#L81

Add one or more of the following Imgui flags:
```
ImGuiWindowFlags.NoBringToFrontOnFocus
ImGuiWindowFlags.NoFocusOnAppearing
ImGuiWindowFlags.NoNavFocus
```

**Comment by rennerdo30** [comment]
Thanks for your feedback.
The changes are currenty only available in my private repository. 
I will submit a new version to the official repository some time later this week.
