### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by allecsc** [rennerdo30/ffxiv-simplecompare#9]
Hi, is there any way you could maybe remake/update this to make it work? I'd really love to have this plugin and it doesn't seem to be working at the moment. Much appreciated!

**Comment by rennerdo30** [comment]
There is already a fork, which will probably update the plugin: https://github.com/53m1k0l0n/ffxiv-simplecompare
Since I am currently not playing FFXIV, updating the plugin is also not as easy.
